/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.absence.salary.slip.application.view;

import java.time.LocalTime;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import com.mycompany.absence.salary.slip.application.models.Absen;
import com.mycompany.absence.salary.slip.application.models.Jabatan;
import com.mycompany.absence.salary.slip.application.models.JabatanPegawai;
import com.mycompany.absence.salary.slip.application.models.Pegawai;
import com.mycompany.absence.salary.slip.application.models.Shift;
import com.mycompany.absence.salary.slip.application.repositories.AbsenRepository;
import com.mycompany.absence.salary.slip.application.repositories.JabatanPegawaiRepository;
import com.mycompany.absence.salary.slip.application.repositories.JabatanRepository;
import com.mycompany.absence.salary.slip.application.repositories.PegawaiRepository;
import com.mycompany.absence.salary.slip.application.repositories.ShiftRepository;
import com.mycompany.absence.salary.slip.application.utils.Response;

/**
 *
 * @author User
 */
public class dashboardAdmin extends javax.swing.JFrame {
    int xx,xy;
    /**
     * Creates new form dashboardAdmin
     */
    public dashboardAdmin() {
        initComponents();
        showAbsensiPegawaiHariini();
        updateJumlahJabatan();
        updateJumlahPegawai();
        updateJumlahShift();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuDashboardAdmin = new javax.swing.JLabel();
        MenupegawaiAdmin = new javax.swing.JLabel();
        MenuPenggajianAdmin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MenuJabatanAdmin = new javax.swing.JLabel();
        MenuShiftAdmin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MenuPerubahanShift = new javax.swing.JLabel();
        MenuDatapegawaiAdmin = new javax.swing.JLabel();
        MenuShiftpegawaiAdmin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MenuGajipegawaiAdmin = new javax.swing.JLabel();
        MenuLogout = new javax.swing.JLabel();
        headerAdmin = new javax.swing.JPanel();
        btmCancel = new javax.swing.JLabel();
        haloAdmin = new javax.swing.JLabel();
        panelUtama_dashboardAdmin = new javax.swing.JPanel();
        panel_jumlahJabatan = new javax.swing.JPanel();
        pTerkini_jumlahJabatan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panel_jumlahPegawai = new javax.swing.JPanel();
        pTerkini_jumlahPegawai = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel_jumlahShift = new javax.swing.JPanel();
        pTerkini_jumlahShift = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_absensiPegawaiHariini = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 640));

        sideBar.setBackground(new java.awt.Color(2, 84, 106));
        sideBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/absence/salary/slip/application/img/logo pesantren (sidebar).png"))); // NOI18N

        MenuDashboardAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuDashboardAdmin.setForeground(new java.awt.Color(255, 255, 255));
        MenuDashboardAdmin.setText("Dashboard");

        MenupegawaiAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenupegawaiAdmin.setForeground(new java.awt.Color(179, 201, 208));
        MenupegawaiAdmin.setText("Pegawai");
        MenupegawaiAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenupegawaiAdminMouseClicked(evt);
            }
        });

        MenuPenggajianAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuPenggajianAdmin.setForeground(new java.awt.Color(179, 201, 208));
        MenuPenggajianAdmin.setText("Penggajian");

        jLabel2.setBackground(new java.awt.Color(179, 201, 208));
        jLabel2.setForeground(new java.awt.Color(179, 201, 208));
        jLabel2.setText("MASTER DATA");

        MenuJabatanAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuJabatanAdmin.setForeground(new java.awt.Color(179, 201, 208));
        MenuJabatanAdmin.setText("Jabatan");

        MenuShiftAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuShiftAdmin.setForeground(new java.awt.Color(179, 201, 208));
        MenuShiftAdmin.setText("Shift");

        jLabel3.setBackground(new java.awt.Color(179, 201, 208));
        jLabel3.setForeground(new java.awt.Color(179, 201, 208));
        jLabel3.setText("TRANSAKSI");

        MenuPerubahanShift.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuPerubahanShift.setForeground(new java.awt.Color(179, 201, 208));
        MenuPerubahanShift.setText("Perubahan Shift");

        MenuDatapegawaiAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuDatapegawaiAdmin.setForeground(new java.awt.Color(179, 201, 208));
        MenuDatapegawaiAdmin.setText("Data Pegawai");

        MenuShiftpegawaiAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuShiftpegawaiAdmin.setForeground(new java.awt.Color(179, 201, 208));
        MenuShiftpegawaiAdmin.setText("Shift Pegawai");

        jLabel6.setBackground(new java.awt.Color(179, 201, 208));
        jLabel6.setForeground(new java.awt.Color(179, 201, 208));
        jLabel6.setText("LAPORAN");

        MenuGajipegawaiAdmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuGajipegawaiAdmin.setForeground(new java.awt.Color(179, 201, 208));
        MenuGajipegawaiAdmin.setText("Gaji Pegawai");

        MenuLogout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuLogout.setForeground(new java.awt.Color(179, 201, 208));
        MenuLogout.setText("Logout");

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sideBarLayout.createSequentialGroup()
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(MenuDashboardAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sideBarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuDatapegawaiAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuPerubahanShift, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuPenggajianAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuJabatanAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenupegawaiAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuShiftAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(sideBarLayout.createSequentialGroup()
                                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(MenuShiftpegawaiAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuGajipegawaiAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(MenuDashboardAdmin)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenupegawaiAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuJabatanAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuShiftAdmin)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuPenggajianAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuPerubahanShift)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuDatapegawaiAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuShiftpegawaiAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuGajipegawaiAdmin)
                .addGap(18, 18, 18)
                .addComponent(MenuLogout)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        headerAdmin.setBackground(new java.awt.Color(255, 255, 255));
        headerAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        headerAdmin.setPreferredSize(new java.awt.Dimension(800, 86));

        btmCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancel.png"))); // NOI18N
        btmCancel.setPreferredSize(new java.awt.Dimension(50, 25));
        btmCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmCancelMouseClicked(evt);
            }
        });

        haloAdmin.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        haloAdmin.setForeground(new java.awt.Color(2, 84, 106));
        haloAdmin.setText("Halo, Admin");

        javax.swing.GroupLayout headerAdminLayout = new javax.swing.GroupLayout(headerAdmin);
        headerAdmin.setLayout(headerAdminLayout);
        headerAdminLayout.setHorizontalGroup(
            headerAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerAdminLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(haloAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 758, Short.MAX_VALUE)
                .addComponent(btmCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerAdminLayout.setVerticalGroup(
            headerAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerAdminLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(haloAdmin)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(headerAdminLayout.createSequentialGroup()
                .addComponent(btmCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_jumlahJabatan.setBackground(new java.awt.Color(255, 255, 255));
        panel_jumlahJabatan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(118, 158, 169), new java.awt.Color(118, 158, 169), null));

        pTerkini_jumlahJabatan.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        pTerkini_jumlahJabatan.setForeground(new java.awt.Color(2, 84, 106));
        pTerkini_jumlahJabatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pTerkini_jumlahJabatan.setText("?");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 84, 106));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Jumlah Jabatan");

        javax.swing.GroupLayout panel_jumlahJabatanLayout = new javax.swing.GroupLayout(panel_jumlahJabatan);
        panel_jumlahJabatan.setLayout(panel_jumlahJabatanLayout);
        panel_jumlahJabatanLayout.setHorizontalGroup(
            panel_jumlahJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
            .addComponent(pTerkini_jumlahJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_jumlahJabatanLayout.setVerticalGroup(
            panel_jumlahJabatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_jumlahJabatanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pTerkini_jumlahJabatan)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_jumlahPegawai.setBackground(new java.awt.Color(255, 255, 255));
        panel_jumlahPegawai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(118, 158, 169), new java.awt.Color(118, 158, 169), null));
        panel_jumlahPegawai.setPreferredSize(new java.awt.Dimension(306, 202));

        pTerkini_jumlahPegawai.setBackground(new java.awt.Color(255, 255, 255));
        pTerkini_jumlahPegawai.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        pTerkini_jumlahPegawai.setForeground(new java.awt.Color(2, 84, 106));
        pTerkini_jumlahPegawai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pTerkini_jumlahPegawai.setText("?");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 84, 106));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah Pegawai");

        javax.swing.GroupLayout panel_jumlahPegawaiLayout = new javax.swing.GroupLayout(panel_jumlahPegawai);
        panel_jumlahPegawai.setLayout(panel_jumlahPegawaiLayout);
        panel_jumlahPegawaiLayout.setHorizontalGroup(
            panel_jumlahPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
            .addComponent(pTerkini_jumlahPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_jumlahPegawaiLayout.setVerticalGroup(
            panel_jumlahPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_jumlahPegawaiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pTerkini_jumlahPegawai)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panel_jumlahShift.setBackground(new java.awt.Color(255, 255, 255));
        panel_jumlahShift.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(118, 158, 169), null, new java.awt.Color(118, 158, 169)));
        panel_jumlahShift.setPreferredSize(new java.awt.Dimension(306, 163));

        pTerkini_jumlahShift.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        pTerkini_jumlahShift.setForeground(new java.awt.Color(2, 84, 106));
        pTerkini_jumlahShift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pTerkini_jumlahShift.setText("?");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 84, 106));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Jumlah Shift");

        javax.swing.GroupLayout panel_jumlahShiftLayout = new javax.swing.GroupLayout(panel_jumlahShift);
        panel_jumlahShift.setLayout(panel_jumlahShiftLayout);
        panel_jumlahShiftLayout.setHorizontalGroup(
            panel_jumlahShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
            .addComponent(pTerkini_jumlahShift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_jumlahShiftLayout.setVerticalGroup(
            panel_jumlahShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_jumlahShiftLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pTerkini_jumlahShift)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_absensiPegawaiHariini.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(118, 158, 169)));
        table_absensiPegawaiHariini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Jabatan", "Nama Shift", "Jam Masuk", "Jam Keluar"
            }
        ));
        jScrollPane1.setViewportView(table_absensiPegawaiHariini);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 84, 106));
        jLabel4.setText("Absensi Pegawai Hari Ini");

        javax.swing.GroupLayout panelUtama_dashboardAdminLayout = new javax.swing.GroupLayout(panelUtama_dashboardAdmin);
        panelUtama_dashboardAdmin.setLayout(panelUtama_dashboardAdminLayout);
        panelUtama_dashboardAdminLayout.setHorizontalGroup(
            panelUtama_dashboardAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtama_dashboardAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUtama_dashboardAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtama_dashboardAdminLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelUtama_dashboardAdminLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(panelUtama_dashboardAdminLayout.createSequentialGroup()
                        .addComponent(panel_jumlahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_jumlahShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(panel_jumlahJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelUtama_dashboardAdminLayout.setVerticalGroup(
            panelUtama_dashboardAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtama_dashboardAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUtama_dashboardAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_jumlahJabatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_jumlahShift, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(panel_jumlahPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panelUtama_dashboardAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(headerAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelUtama_dashboardAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btmCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btmCancelMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void MenupegawaiAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenupegawaiAdminMouseClicked
            masterData_Admin dashboard = new masterData_Admin(); // Membuat objek form tujuan
            dashboard.setVisible(true);                      // Menampilkan form tujuan
            this.dispose();                                  // Menutup form saat ini (opsional)
    }//GEN-LAST:event_MenupegawaiAdminMouseClicked

    private void showAbsensiPegawaiHariini() {
        AbsenRepository absenRepository = new AbsenRepository();
        ShiftRepository shiftRepository = new ShiftRepository();
        PegawaiRepository pegawaiRepository = new PegawaiRepository();
        JabatanRepository jabatanRepository = new JabatanRepository();
        JabatanPegawaiRepository jabatanPegawaiRepository = new JabatanPegawaiRepository();

        Response<ArrayList<Absen>> findAllAbsensi = absenRepository.findAll();

        String[] columnNames = {"Nama", "Jabatan", "Nama Shift", "Jam Masuk", "Jam Keluar"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        if (findAllAbsensi.isSuccess() && findAllAbsensi.getData() != null) {
            for (Absen absen : findAllAbsensi.getData()) {
                String namaPegawai = "-";
                String namaJabatan = "-";
                String namaShift = "-";

                // Ambil data pegawai
                Response<Pegawai> responsePegawai = pegawaiRepository.findById(absen.getIdPegawai());
                if (responsePegawai != null && responsePegawai.getData() != null) {
                    Pegawai pegawai = responsePegawai.getData();
                    namaPegawai = pegawai.getNama();
                    System.out.println("Pegawai: " + namaPegawai + " (ID: " + pegawai.getId() + ")");

                    // Ambil jabatan pegawai
                    Response<ArrayList<JabatanPegawai>> responseJabatanPegawai = jabatanPegawaiRepository.findByPegawaiId(absen.getIdPegawai());
                    if (responseJabatanPegawai != null && responseJabatanPegawai.getData() != null && !responseJabatanPegawai.getData().isEmpty()) {
                        JabatanPegawai jabatanPegawai = responseJabatanPegawai.getData().get(0); // Ambil jabatan pertama
            
                        // Ambil data jabatan
                        Response<Jabatan> responseJabatan = jabatanRepository.findById(jabatanPegawai.getIdJabatan());
                        if (responseJabatan != null && responseJabatan.getData() != null) {
                            namaJabatan = responseJabatan.getData().getNamaJabatan();
                        } else {
                            System.out.println("-> Jabatan ID " + jabatanPegawai.getIdJabatan() + " tidak ditemukan.");
                        }
                    } else {
                        System.out.println("-> Tidak ada jabatan untuk pegawai ID " + pegawai.getId());
                    }
                } else {
                    System.out.println("Pegawai dengan ID " + absen.getIdPegawai() + " tidak ditemukan.");
                }

                // Ambil data shift
                Response<Shift> responseShift = shiftRepository.findById(absen.getIdShift());
                if (responseShift != null && responseShift.getData() != null) {
                    namaShift = responseShift.getData().getNamaShift();
                }

                // Masukkan ke dalam tabel
                Object[] row = {
                    namaPegawai,
                    namaJabatan,
                    namaShift,
                    absen.getJamMasuk(),
                    absen.getJamKeluar()
                };

                model.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data absensi pegawai: " + findAllAbsensi.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        table_absensiPegawaiHariini.setModel(model);
    }

    private void updateJumlahJabatan() {
        JabatanRepository jabatanRepository = new JabatanRepository();
        Response<ArrayList<Jabatan>> response = jabatanRepository.findAll();
        if (response.isSuccess() && response.getData() != null) {
            pTerkini_jumlahJabatan.setText(String.valueOf(response.getData().size()));
        } else {
            pTerkini_jumlahJabatan.setText("0");
        }
    }

    private void updateJumlahPegawai() {
        PegawaiRepository pegawaiRepository = new PegawaiRepository();
        Response<ArrayList<Pegawai>> response = pegawaiRepository.findAll();
        if (response.isSuccess() && response.getData() != null) {
            pTerkini_jumlahPegawai.setText(String.valueOf(response.getData().size()));
        } else {
            pTerkini_jumlahPegawai.setText("0");
        }
    }

    private void updateJumlahShift() {
        ShiftRepository shiftRepository = new ShiftRepository();
        Response<ArrayList<Shift>> response = shiftRepository.findAll();
        if (response.isSuccess() && response.getData() != null) {
            pTerkini_jumlahShift.setText(String.valueOf(response.getData().size()));
        } else {
            pTerkini_jumlahShift.setText("0");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuDashboardAdmin;
    private javax.swing.JLabel MenuDatapegawaiAdmin;
    private javax.swing.JLabel MenuGajipegawaiAdmin;
    private javax.swing.JLabel MenuJabatanAdmin;
    private javax.swing.JLabel MenuLogout;
    private javax.swing.JLabel MenuPenggajianAdmin;
    private javax.swing.JLabel MenuPerubahanShift;
    private javax.swing.JLabel MenuShiftAdmin;
    private javax.swing.JLabel MenuShiftpegawaiAdmin;
    private javax.swing.JLabel MenupegawaiAdmin;
    private javax.swing.JLabel btmCancel;
    private javax.swing.JLabel haloAdmin;
    private javax.swing.JPanel headerAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pTerkini_jumlahJabatan;
    private javax.swing.JLabel pTerkini_jumlahPegawai;
    private javax.swing.JLabel pTerkini_jumlahShift;
    private javax.swing.JPanel panelUtama_dashboardAdmin;
    private javax.swing.JPanel panel_jumlahJabatan;
    private javax.swing.JPanel panel_jumlahPegawai;
    private javax.swing.JPanel panel_jumlahShift;
    private javax.swing.JPanel sideBar;
    private javax.swing.JTable table_absensiPegawaiHariini;
    // End of variables declaration//GEN-END:variables
}