/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.absence.salary.slip.application.view;

/**
 *
 * @author User
 */
public class form_masterShift extends javax.swing.JPanel {

    /**
     * Creates new form form_masterJabatan
     */
    public form_masterShift() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataShift = new javax.swing.JPanel();
        panelUtama_masterShift_Admin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dataShift = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btn_tambah_masterShift = new javax.swing.JButton();
        btn_hapus_masterShift = new javax.swing.JButton();
        btn_batal_masterShift = new javax.swing.JButton();
        tambahShift = new javax.swing.JPanel();
        panelKedua_masterShift_Admin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_simpan_masterJabatan = new javax.swing.JButton();
        btn_batal_masterPegawai2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jText_namaShift = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jText_jamMasuk = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jText_jamKeluar = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(900, 525));

        mainPanel.setLayout(new java.awt.CardLayout());

        table_dataShift.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(118, 158, 169)));
        table_dataShift.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Shift", "Jam Masuk", "Jam Keluar"
            }
        ));
        jScrollPane1.setViewportView(table_dataShift);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 84, 106));
        jLabel4.setText("Data Shift");

        btn_tambah_masterShift.setText("TAMBAH");
        btn_tambah_masterShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_masterShiftActionPerformed(evt);
            }
        });

        btn_hapus_masterShift.setText("HAPUS");
        btn_hapus_masterShift.setToolTipText("");
        btn_hapus_masterShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus_masterShiftActionPerformed(evt);
            }
        });

        btn_batal_masterShift.setText("BATAL");
        btn_batal_masterShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_masterShiftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUtama_masterShift_AdminLayout = new javax.swing.GroupLayout(panelUtama_masterShift_Admin);
        panelUtama_masterShift_Admin.setLayout(panelUtama_masterShift_AdminLayout);
        panelUtama_masterShift_AdminLayout.setHorizontalGroup(
            panelUtama_masterShift_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtama_masterShift_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUtama_masterShift_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtama_masterShift_AdminLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelUtama_masterShift_AdminLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(panelUtama_masterShift_AdminLayout.createSequentialGroup()
                        .addComponent(btn_tambah_masterShift)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hapus_masterShift)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batal_masterShift)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelUtama_masterShift_AdminLayout.setVerticalGroup(
            panelUtama_masterShift_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtama_masterShift_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(37, 37, 37)
                .addGroup(panelUtama_masterShift_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah_masterShift)
                    .addComponent(btn_hapus_masterShift)
                    .addComponent(btn_batal_masterShift))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dataShiftLayout = new javax.swing.GroupLayout(dataShift);
        dataShift.setLayout(dataShiftLayout);
        dataShiftLayout.setHorizontalGroup(
            dataShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(dataShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataShiftLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelUtama_masterShift_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dataShiftLayout.setVerticalGroup(
            dataShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
            .addGroup(dataShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dataShiftLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelUtama_masterShift_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        mainPanel.add(dataShift, "card2");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 84, 106));
        jLabel5.setText("Tambah Data Shift");

        btn_simpan_masterJabatan.setText("SIMPAN");
        btn_simpan_masterJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_masterJabatanActionPerformed(evt);
            }
        });

        btn_batal_masterPegawai2.setText("BATAL");
        btn_batal_masterPegawai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_masterPegawai2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nama Shift");

        jText_namaShift.setText("jTextField1");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Jam Masuk");

        jText_jamMasuk.setText("jTextField1");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Jam Keluar");

        jText_jamKeluar.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jText_namaShift, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jText_jamMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jText_jamKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_namaShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_jamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_jamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelKedua_masterShift_AdminLayout = new javax.swing.GroupLayout(panelKedua_masterShift_Admin);
        panelKedua_masterShift_Admin.setLayout(panelKedua_masterShift_AdminLayout);
        panelKedua_masterShift_AdminLayout.setHorizontalGroup(
            panelKedua_masterShift_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKedua_masterShift_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKedua_masterShift_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelKedua_masterShift_AdminLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelKedua_masterShift_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelKedua_masterShift_AdminLayout.createSequentialGroup()
                                .addComponent(btn_simpan_masterJabatan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_batal_masterPegawai2))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 500, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelKedua_masterShift_AdminLayout.setVerticalGroup(
            panelKedua_masterShift_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKedua_masterShift_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(panelKedua_masterShift_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan_masterJabatan)
                    .addComponent(btn_batal_masterPegawai2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout tambahShiftLayout = new javax.swing.GroupLayout(tambahShift);
        tambahShift.setLayout(tambahShiftLayout);
        tambahShiftLayout.setHorizontalGroup(
            tambahShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahShiftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelKedua_masterShift_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tambahShiftLayout.setVerticalGroup(
            tambahShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahShiftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelKedua_masterShift_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(tambahShift, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambah_masterShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_masterShiftActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahShift);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_tambah_masterShiftActionPerformed

    private void btn_hapus_masterShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus_masterShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapus_masterShiftActionPerformed

    private void btn_batal_masterShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_masterShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batal_masterShiftActionPerformed

    private void btn_simpan_masterJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_masterJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpan_masterJabatanActionPerformed

    private void btn_batal_masterPegawai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_masterPegawai2ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(dataShift);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_batal_masterPegawai2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal_masterPegawai2;
    private javax.swing.JButton btn_batal_masterShift;
    private javax.swing.JButton btn_hapus_masterShift;
    private javax.swing.JButton btn_simpan_masterJabatan;
    private javax.swing.JButton btn_tambah_masterShift;
    private javax.swing.JPanel dataShift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jText_jamKeluar;
    private javax.swing.JTextField jText_jamMasuk;
    private javax.swing.JTextField jText_namaShift;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelKedua_masterShift_Admin;
    private javax.swing.JPanel panelUtama_masterShift_Admin;
    private javax.swing.JTable table_dataShift;
    private javax.swing.JPanel tambahShift;
    // End of variables declaration//GEN-END:variables
}
