/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
public class DashboardKaryawanFrame extends JFrame {
    private Karyawan karyawan;
    private DefaultTableModel model;
    
    /**
     * Creates new form DashboardKaryawanFrame
     */
        public DashboardKaryawanFrame(Karyawan karyawan) {
        this.karyawan = karyawan;
        setTitle("Dashboard Karyawan - " + karyawan.getNama());
        setSize(600, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // Panel untuk tabel
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());

        String[] columnNames = {"Tanggal", "Hari", "Jam", "Status Absensi"};
        model = new DefaultTableModel(columnNames, 0);
        JTable table = new JTable(model);
        JScrollPane scrollPane = new JScrollPane(table);
        panel.add(scrollPane, BorderLayout.CENTER);

        // Tombol untuk absensi
        JButton btnAbsensi = new JButton("Absensi");
        btnAbsensi.setIcon(new ImageIcon("resources/absensi_icon.png")); // Ganti dengan path ikon
        btnAbsensi.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                new AbsensiFrame(karyawan, model);
            }
        });

        // Tombol logout
        JButton btnLogout = new JButton("Log Out");
        btnLogout.setIcon(new ImageIcon("resources/logout_icon.png")); // Ganti dengan path ikon
        btnLogout.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.YES_OPTION) {
                    new LoginKaryawanFrame();
                    dispose();
                }
            }
        });

        // Panel untuk tombol
        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnAbsensi);
        buttonPanel.add(btnLogout);

        // Menambahkan panel ke frame
        add(panel, BorderLayout.CENTER);
        add(buttonPanel, BorderLayout.SOUTH);

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
