/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author user
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabDashboardAdmin = new javax.swing.JTabbedPane();
        panelAdmin = new javax.swing.JPanel();
        panelMainContent = new javax.swing.JPanel();
        lblDashboardAdmin = new javax.swing.JLabel();
        lblDataPegawai = new javax.swing.JLabel();
        panelBodyTabel = new javax.swing.JPanel();
        lblRekapAbsensi = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRekapAbsensi = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnEditAbsensi = new javax.swing.JButton();
        btnHapusAbsensi = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDataPegawai = new javax.swing.JTable();
        panelSidebar = new javax.swing.JPanel();
        btnAbsensi = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblLogoPondok = new javax.swing.JLabel();
        panelShiftPegawai = new javax.swing.JPanel();
        panelMainContent1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShiftPegawai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAdminNama = new javax.swing.JLabel();
        lblAdminJabatan = new javax.swing.JLabel();
        lblAdminJamMasuk = new javax.swing.JLabel();
        lblAdminJamKeluar = new javax.swing.JLabel();
        cbPegawai = new javax.swing.JComboBox<>();
        spinnerJamMasuk = new javax.swing.JSpinner();
        spinnerJamKeluar = new javax.swing.JSpinner();
        btnSimpanShift = new javax.swing.JButton();
        panelLaporan = new javax.swing.JPanel();
        panelMainContent2 = new javax.swing.JPanel();
        panelSlipGaji = new javax.swing.JPanel();
        panelMainContent3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(725, 600));

        tabDashboardAdmin.setBackground(new java.awt.Color(255, 255, 255));

        panelAdmin.setBackground(new java.awt.Color(255, 255, 255));

        panelMainContent.setBackground(new java.awt.Color(0, 102, 102));

        lblDashboardAdmin.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lblDashboardAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboardAdmin.setText("DASHBOARD ADMIN");

        lblDataPegawai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDataPegawai.setForeground(new java.awt.Color(255, 255, 255));
        lblDataPegawai.setText("DATA PEGAWAI");

        panelBodyTabel.setBackground(new java.awt.Color(255, 255, 255));

        lblRekapAbsensi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRekapAbsensi.setForeground(new java.awt.Color(0, 102, 102));
        lblRekapAbsensi.setText("RECAP ABSENSI");

        tblRekapAbsensi.setBackground(new java.awt.Color(204, 255, 255));
        tblRekapAbsensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "ID", "Foto", "Jabatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblRekapAbsensi);

        jLabel13.setText("AKSI");

        btnEditAbsensi.setBackground(new java.awt.Color(0, 153, 255));
        btnEditAbsensi.setText("EDIT");
        btnEditAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAbsensijButton2ActionPerformed(evt);
            }
        });

        btnHapusAbsensi.setBackground(new java.awt.Color(255, 0, 51));
        btnHapusAbsensi.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnHapusAbsensi.setText("HAPUS");
        btnHapusAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusAbsensijButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBodyTabelLayout = new javax.swing.GroupLayout(panelBodyTabel);
        panelBodyTabel.setLayout(panelBodyTabelLayout);
        panelBodyTabelLayout.setHorizontalGroup(
            panelBodyTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyTabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBodyTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBodyTabelLayout.createSequentialGroup()
                        .addComponent(lblRekapAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBodyTabelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(panelBodyTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBodyTabelLayout.createSequentialGroup()
                                .addComponent(btnEditAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelBodyTabelLayout.setVerticalGroup(
            panelBodyTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBodyTabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRekapAbsensi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBodyTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBodyTabelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBodyTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapusAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        tblDataPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tanggal", "ID", "Nama", "Jam Masuk", "Jam Keluar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblDataPegawai);

        javax.swing.GroupLayout panelMainContentLayout = new javax.swing.GroupLayout(panelMainContent);
        panelMainContent.setLayout(panelMainContentLayout);
        panelMainContentLayout.setHorizontalGroup(
            panelMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainContentLayout.createSequentialGroup()
                .addGroup(panelMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainContentLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lblDashboardAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainContentLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBodyTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelMainContentLayout.setVerticalGroup(
            panelMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainContentLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblDashboardAdmin)
                .addGap(34, 34, 34)
                .addComponent(lblDataPegawai)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBodyTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        panelSidebar.setBackground(new java.awt.Color(0, 153, 153));

        btnAbsensi.setText("ABSENSI");
        btnAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsensiActionPerformed(evt);
            }
        });

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblLogoPondok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSEST/Plakat Ma'had MTSN 3 2.png"))); // NOI18N

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogoPondok, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblLogoPondok)
                .addGap(59, 59, 59)
                .addComponent(btnAbsensi)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminLayout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabDashboardAdmin.addTab("ADMIN", panelAdmin);

        panelMainContent1.setBackground(new java.awt.Color(0, 102, 102));

        tblShiftPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "ID", "Jam Masuk", "Jam Keluar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblShiftPegawai);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DAFTAR SHIFT PEGAWAI");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELAMAT DATANG ADMIN");

        lblAdminNama.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminNama.setText("Nama");

        lblAdminJabatan.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminJabatan.setText("Jabatan");

        lblAdminJamMasuk.setBackground(new java.awt.Color(255, 255, 255));
        lblAdminJamMasuk.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminJamMasuk.setText("Jam Masuk");

        lblAdminJamKeluar.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminJamKeluar.setText("Jam Keluar");

        cbPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSimpanShift.setBackground(new java.awt.Color(51, 255, 255));
        btnSimpanShift.setText("SIMPAN");

        javax.swing.GroupLayout panelMainContent1Layout = new javax.swing.GroupLayout(panelMainContent1);
        panelMainContent1.setLayout(panelMainContent1Layout);
        panelMainContent1Layout.setHorizontalGroup(
            panelMainContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainContent1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelMainContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMainContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblAdminJabatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(lblAdminNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMainContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblAdminJamKeluar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAdminJamMasuk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelMainContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainContent1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMainContent1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(panelMainContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelMainContent1Layout.createSequentialGroup()
                                .addComponent(cbPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinnerJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSimpanShift)))
                        .addContainerGap(169, Short.MAX_VALUE))))
        );
        panelMainContent1Layout.setVerticalGroup(
            panelMainContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainContent1Layout.createSequentialGroup()
                .addGroup(panelMainContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainContent1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblAdminNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAdminJabatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAdminJamMasuk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAdminJamKeluar))
                    .addGroup(panelMainContent1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelMainContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainContent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinnerJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinnerJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSimpanShift))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelShiftPegawaiLayout = new javax.swing.GroupLayout(panelShiftPegawai);
        panelShiftPegawai.setLayout(panelShiftPegawaiLayout);
        panelShiftPegawaiLayout.setHorizontalGroup(
            panelShiftPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainContent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelShiftPegawaiLayout.setVerticalGroup(
            panelShiftPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainContent1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabDashboardAdmin.addTab("SHIFT PEGAWAI", panelShiftPegawai);

        panelMainContent2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelMainContent2Layout = new javax.swing.GroupLayout(panelMainContent2);
        panelMainContent2.setLayout(panelMainContent2Layout);
        panelMainContent2Layout.setHorizontalGroup(
            panelMainContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        panelMainContent2Layout.setVerticalGroup(
            panelMainContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMainContent2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainContent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabDashboardAdmin.addTab("LAPORAN", panelLaporan);

        panelMainContent3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout panelMainContent3Layout = new javax.swing.GroupLayout(panelMainContent3);
        panelMainContent3.setLayout(panelMainContent3Layout);
        panelMainContent3Layout.setHorizontalGroup(
            panelMainContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
        );
        panelMainContent3Layout.setVerticalGroup(
            panelMainContent3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSlipGajiLayout = new javax.swing.GroupLayout(panelSlipGaji);
        panelSlipGaji.setLayout(panelSlipGajiLayout);
        panelSlipGajiLayout.setHorizontalGroup(
            panelSlipGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainContent3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSlipGajiLayout.setVerticalGroup(
            panelSlipGajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMainContent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabDashboardAdmin.addTab("SLIP GAJI", panelSlipGaji);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabDashboardAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabDashboardAdmin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsensiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbsensiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHapusAbsensijButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusAbsensijButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusAbsensijButton3ActionPerformed

    private void btnEditAbsensijButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAbsensijButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditAbsensijButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            lblDashboardAdminDashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbsensi;
    private javax.swing.JButton btnEditAbsensi;
    private javax.swing.JButton btnHapusAbsensi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSimpanShift;
    private javax.swing.JComboBox<String> cbPegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAdminJabatan;
    private javax.swing.JLabel lblAdminJamKeluar;
    private javax.swing.JLabel lblAdminJamMasuk;
    private javax.swing.JLabel lblAdminNama;
    private javax.swing.JLabel lblDashboardAdmin;
    private javax.swing.JLabel lblDataPegawai;
    private javax.swing.JLabel lblLogoPondok;
    private javax.swing.JLabel lblRekapAbsensi;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelBodyTabel;
    private javax.swing.JPanel panelLaporan;
    private javax.swing.JPanel panelMainContent;
    private javax.swing.JPanel panelMainContent1;
    private javax.swing.JPanel panelMainContent2;
    private javax.swing.JPanel panelMainContent3;
    private javax.swing.JPanel panelShiftPegawai;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelSlipGaji;
    private javax.swing.JSpinner spinnerJamKeluar;
    private javax.swing.JSpinner spinnerJamMasuk;
    private javax.swing.JTabbedPane tabDashboardAdmin;
    private javax.swing.JTable tblDataPegawai;
    private javax.swing.JTable tblRekapAbsensi;
    private javax.swing.JTable tblShiftPegawai;
    // End of variables declaration//GEN-END:variables
}
